package com.inclination.scaffold.infrastraction.repository;

import com.inclination.scaffold.api.response.menuresource.MenuResourceResponse;
import com.inclination.scaffold.infrastraction.repository.po.MenuResource;
import com.inclination.scaffold.infrastraction.repository.po.MenuResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MenuResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    long countByExample(MenuResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int deleteByExample(MenuResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int insert(MenuResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int insertSelective(MenuResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    List<MenuResource> selectByExampleWithRowbounds(MenuResourceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    List<MenuResource> selectByExample(MenuResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    MenuResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") MenuResource record, @Param("example") MenuResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int updateByExample(@Param("record") MenuResource record, @Param("example") MenuResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int updateByPrimaryKeySelective(MenuResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int updateByPrimaryKey(MenuResource record);

    /**
     * 对相同的资源菜单关系进行计数
     * @param po 条件集合
     * @return 计数
     */ 
	int countBySame(MenuResource po);
	/**
	 * 查询所有的数据集合
	 * @return 返回所有
	 */
	List<MenuResourceResponse> findAll();
}