package com.inclination.scaffold.infrastraction.repository;

import com.inclination.scaffold.infrastraction.repository.po.Role;
import com.inclination.scaffold.infrastraction.repository.po.Tmenu;
import com.inclination.scaffold.infrastraction.repository.po.TmenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TmenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    long countByExample(TmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int deleteByExample(TmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int insert(Tmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int insertSelective(Tmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    List<Tmenu> selectByExampleWithRowbounds(TmenuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    List<Tmenu> selectByExample(TmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    Tmenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tmenu record, @Param("example") TmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int updateByExample(@Param("record") Tmenu record, @Param("example") TmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int updateByPrimaryKeySelective(Tmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    int updateByPrimaryKey(Tmenu record);

    /**
     * 模糊查询菜单
     * @param po
     * @return
     */
	List<Tmenu> selectBySelective(Tmenu po);

	/**
	 * 根据名称计数
	 * @param po
	 * @return
	 */
	int countByName(Tmenu po);
}