package com.inclination.scaffold.infrastraction.repository;

import com.inclination.scaffold.infrastraction.repository.po.Toolprojecturl;
import com.inclination.scaffold.infrastraction.repository.po.ToolprojecturlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ToolprojecturlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    long countByExample(ToolprojecturlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    int deleteByExample(ToolprojecturlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    int insert(Toolprojecturl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    int insertSelective(Toolprojecturl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    List<Toolprojecturl> selectByExampleWithRowbounds(ToolprojecturlExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    List<Toolprojecturl> selectByExample(ToolprojecturlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    Toolprojecturl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") Toolprojecturl record, @Param("example") ToolprojecturlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    int updateByExample(@Param("record") Toolprojecturl record, @Param("example") ToolprojecturlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    int updateByPrimaryKeySelective(Toolprojecturl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    int updateByPrimaryKey(Toolprojecturl record);
}