package com.inclination.scaffold.infrastraction.repository.po;

import java.io.Serializable;

public class MenuResource implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_resource.id
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_resource.menusid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private Integer menusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_resource.resourcesid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private Integer resourcesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_resource.id
     *
     * @return the value of menu_resource.id
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_resource.id
     *
     * @param id the value for menu_resource.id
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_resource.menusid
     *
     * @return the value of menu_resource.menusid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public Integer getMenusid() {
        return menusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_resource.menusid
     *
     * @param menusid the value for menu_resource.menusid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public void setMenusid(Integer menusid) {
        this.menusid = menusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_resource.resourcesid
     *
     * @return the value of menu_resource.resourcesid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public Integer getResourcesid() {
        return resourcesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_resource.resourcesid
     *
     * @param resourcesid the value for menu_resource.resourcesid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public void setResourcesid(Integer resourcesid) {
        this.resourcesid = resourcesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_resource
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", menusid=").append(menusid);
        sb.append(", resourcesid=").append(resourcesid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}