package com.inclination.scaffold.infrastraction.repository.po;

import java.io.Serializable;
import java.util.Date;

public class Project implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.loginid
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private String loginid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.giturl
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private String giturl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.jenkinsurl
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private String jenkinsurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.apollourl
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private String apollourl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.artifactid
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private String artifactid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.groupid
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private String groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.version
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.gitorg
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private String gitorg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.apolloorg
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private String apolloorg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.createtime
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.loginid
     *
     * @return the value of project.loginid
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public String getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.loginid
     *
     * @param loginid the value for project.loginid
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid == null ? null : loginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.giturl
     *
     * @return the value of project.giturl
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public String getGiturl() {
        return giturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.giturl
     *
     * @param giturl the value for project.giturl
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setGiturl(String giturl) {
        this.giturl = giturl == null ? null : giturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.jenkinsurl
     *
     * @return the value of project.jenkinsurl
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public String getJenkinsurl() {
        return jenkinsurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.jenkinsurl
     *
     * @param jenkinsurl the value for project.jenkinsurl
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setJenkinsurl(String jenkinsurl) {
        this.jenkinsurl = jenkinsurl == null ? null : jenkinsurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.apollourl
     *
     * @return the value of project.apollourl
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public String getApollourl() {
        return apollourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.apollourl
     *
     * @param apollourl the value for project.apollourl
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setApollourl(String apollourl) {
        this.apollourl = apollourl == null ? null : apollourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.artifactid
     *
     * @return the value of project.artifactid
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public String getArtifactid() {
        return artifactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.artifactid
     *
     * @param artifactid the value for project.artifactid
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setArtifactid(String artifactid) {
        this.artifactid = artifactid == null ? null : artifactid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.groupid
     *
     * @return the value of project.groupid
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.groupid
     *
     * @param groupid the value for project.groupid
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.version
     *
     * @return the value of project.version
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.version
     *
     * @param version the value for project.version
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.gitorg
     *
     * @return the value of project.gitorg
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public String getGitorg() {
        return gitorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.gitorg
     *
     * @param gitorg the value for project.gitorg
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setGitorg(String gitorg) {
        this.gitorg = gitorg == null ? null : gitorg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.apolloorg
     *
     * @return the value of project.apolloorg
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public String getApolloorg() {
        return apolloorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.apolloorg
     *
     * @param apolloorg the value for project.apolloorg
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setApolloorg(String apolloorg) {
        this.apolloorg = apolloorg == null ? null : apolloorg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.createtime
     *
     * @return the value of project.createtime
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.createtime
     *
     * @param createtime the value for project.createtime
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginid=").append(loginid);
        sb.append(", giturl=").append(giturl);
        sb.append(", jenkinsurl=").append(jenkinsurl);
        sb.append(", apollourl=").append(apollourl);
        sb.append(", artifactid=").append(artifactid);
        sb.append(", groupid=").append(groupid);
        sb.append(", version=").append(version);
        sb.append(", gitorg=").append(gitorg);
        sb.append(", apolloorg=").append(apolloorg);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}