package com.inclination.scaffold.infrastraction.repository.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLoginidIsNull() {
            addCriterion("loginid is null");
            return (Criteria) this;
        }

        public Criteria andLoginidIsNotNull() {
            addCriterion("loginid is not null");
            return (Criteria) this;
        }

        public Criteria andLoginidEqualTo(String value) {
            addCriterion("loginid =", value, "loginid");
            return (Criteria) this;
        }

        public Criteria andLoginidNotEqualTo(String value) {
            addCriterion("loginid <>", value, "loginid");
            return (Criteria) this;
        }

        public Criteria andLoginidGreaterThan(String value) {
            addCriterion("loginid >", value, "loginid");
            return (Criteria) this;
        }

        public Criteria andLoginidGreaterThanOrEqualTo(String value) {
            addCriterion("loginid >=", value, "loginid");
            return (Criteria) this;
        }

        public Criteria andLoginidLessThan(String value) {
            addCriterion("loginid <", value, "loginid");
            return (Criteria) this;
        }

        public Criteria andLoginidLessThanOrEqualTo(String value) {
            addCriterion("loginid <=", value, "loginid");
            return (Criteria) this;
        }

        public Criteria andLoginidLike(String value) {
            addCriterion("loginid like", value, "loginid");
            return (Criteria) this;
        }

        public Criteria andLoginidNotLike(String value) {
            addCriterion("loginid not like", value, "loginid");
            return (Criteria) this;
        }

        public Criteria andLoginidIn(List<String> values) {
            addCriterion("loginid in", values, "loginid");
            return (Criteria) this;
        }

        public Criteria andLoginidNotIn(List<String> values) {
            addCriterion("loginid not in", values, "loginid");
            return (Criteria) this;
        }

        public Criteria andLoginidBetween(String value1, String value2) {
            addCriterion("loginid between", value1, value2, "loginid");
            return (Criteria) this;
        }

        public Criteria andLoginidNotBetween(String value1, String value2) {
            addCriterion("loginid not between", value1, value2, "loginid");
            return (Criteria) this;
        }

        public Criteria andGiturlIsNull() {
            addCriterion("giturl is null");
            return (Criteria) this;
        }

        public Criteria andGiturlIsNotNull() {
            addCriterion("giturl is not null");
            return (Criteria) this;
        }

        public Criteria andGiturlEqualTo(String value) {
            addCriterion("giturl =", value, "giturl");
            return (Criteria) this;
        }

        public Criteria andGiturlNotEqualTo(String value) {
            addCriterion("giturl <>", value, "giturl");
            return (Criteria) this;
        }

        public Criteria andGiturlGreaterThan(String value) {
            addCriterion("giturl >", value, "giturl");
            return (Criteria) this;
        }

        public Criteria andGiturlGreaterThanOrEqualTo(String value) {
            addCriterion("giturl >=", value, "giturl");
            return (Criteria) this;
        }

        public Criteria andGiturlLessThan(String value) {
            addCriterion("giturl <", value, "giturl");
            return (Criteria) this;
        }

        public Criteria andGiturlLessThanOrEqualTo(String value) {
            addCriterion("giturl <=", value, "giturl");
            return (Criteria) this;
        }

        public Criteria andGiturlLike(String value) {
            addCriterion("giturl like", value, "giturl");
            return (Criteria) this;
        }

        public Criteria andGiturlNotLike(String value) {
            addCriterion("giturl not like", value, "giturl");
            return (Criteria) this;
        }

        public Criteria andGiturlIn(List<String> values) {
            addCriterion("giturl in", values, "giturl");
            return (Criteria) this;
        }

        public Criteria andGiturlNotIn(List<String> values) {
            addCriterion("giturl not in", values, "giturl");
            return (Criteria) this;
        }

        public Criteria andGiturlBetween(String value1, String value2) {
            addCriterion("giturl between", value1, value2, "giturl");
            return (Criteria) this;
        }

        public Criteria andGiturlNotBetween(String value1, String value2) {
            addCriterion("giturl not between", value1, value2, "giturl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlIsNull() {
            addCriterion("jenkinsurl is null");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlIsNotNull() {
            addCriterion("jenkinsurl is not null");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlEqualTo(String value) {
            addCriterion("jenkinsurl =", value, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlNotEqualTo(String value) {
            addCriterion("jenkinsurl <>", value, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlGreaterThan(String value) {
            addCriterion("jenkinsurl >", value, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlGreaterThanOrEqualTo(String value) {
            addCriterion("jenkinsurl >=", value, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlLessThan(String value) {
            addCriterion("jenkinsurl <", value, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlLessThanOrEqualTo(String value) {
            addCriterion("jenkinsurl <=", value, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlLike(String value) {
            addCriterion("jenkinsurl like", value, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlNotLike(String value) {
            addCriterion("jenkinsurl not like", value, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlIn(List<String> values) {
            addCriterion("jenkinsurl in", values, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlNotIn(List<String> values) {
            addCriterion("jenkinsurl not in", values, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlBetween(String value1, String value2) {
            addCriterion("jenkinsurl between", value1, value2, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andJenkinsurlNotBetween(String value1, String value2) {
            addCriterion("jenkinsurl not between", value1, value2, "jenkinsurl");
            return (Criteria) this;
        }

        public Criteria andApollourlIsNull() {
            addCriterion("apollourl is null");
            return (Criteria) this;
        }

        public Criteria andApollourlIsNotNull() {
            addCriterion("apollourl is not null");
            return (Criteria) this;
        }

        public Criteria andApollourlEqualTo(String value) {
            addCriterion("apollourl =", value, "apollourl");
            return (Criteria) this;
        }

        public Criteria andApollourlNotEqualTo(String value) {
            addCriterion("apollourl <>", value, "apollourl");
            return (Criteria) this;
        }

        public Criteria andApollourlGreaterThan(String value) {
            addCriterion("apollourl >", value, "apollourl");
            return (Criteria) this;
        }

        public Criteria andApollourlGreaterThanOrEqualTo(String value) {
            addCriterion("apollourl >=", value, "apollourl");
            return (Criteria) this;
        }

        public Criteria andApollourlLessThan(String value) {
            addCriterion("apollourl <", value, "apollourl");
            return (Criteria) this;
        }

        public Criteria andApollourlLessThanOrEqualTo(String value) {
            addCriterion("apollourl <=", value, "apollourl");
            return (Criteria) this;
        }

        public Criteria andApollourlLike(String value) {
            addCriterion("apollourl like", value, "apollourl");
            return (Criteria) this;
        }

        public Criteria andApollourlNotLike(String value) {
            addCriterion("apollourl not like", value, "apollourl");
            return (Criteria) this;
        }

        public Criteria andApollourlIn(List<String> values) {
            addCriterion("apollourl in", values, "apollourl");
            return (Criteria) this;
        }

        public Criteria andApollourlNotIn(List<String> values) {
            addCriterion("apollourl not in", values, "apollourl");
            return (Criteria) this;
        }

        public Criteria andApollourlBetween(String value1, String value2) {
            addCriterion("apollourl between", value1, value2, "apollourl");
            return (Criteria) this;
        }

        public Criteria andApollourlNotBetween(String value1, String value2) {
            addCriterion("apollourl not between", value1, value2, "apollourl");
            return (Criteria) this;
        }

        public Criteria andArtifactidIsNull() {
            addCriterion("artifactid is null");
            return (Criteria) this;
        }

        public Criteria andArtifactidIsNotNull() {
            addCriterion("artifactid is not null");
            return (Criteria) this;
        }

        public Criteria andArtifactidEqualTo(String value) {
            addCriterion("artifactid =", value, "artifactid");
            return (Criteria) this;
        }

        public Criteria andArtifactidNotEqualTo(String value) {
            addCriterion("artifactid <>", value, "artifactid");
            return (Criteria) this;
        }

        public Criteria andArtifactidGreaterThan(String value) {
            addCriterion("artifactid >", value, "artifactid");
            return (Criteria) this;
        }

        public Criteria andArtifactidGreaterThanOrEqualTo(String value) {
            addCriterion("artifactid >=", value, "artifactid");
            return (Criteria) this;
        }

        public Criteria andArtifactidLessThan(String value) {
            addCriterion("artifactid <", value, "artifactid");
            return (Criteria) this;
        }

        public Criteria andArtifactidLessThanOrEqualTo(String value) {
            addCriterion("artifactid <=", value, "artifactid");
            return (Criteria) this;
        }

        public Criteria andArtifactidLike(String value) {
            addCriterion("artifactid like", value, "artifactid");
            return (Criteria) this;
        }

        public Criteria andArtifactidNotLike(String value) {
            addCriterion("artifactid not like", value, "artifactid");
            return (Criteria) this;
        }

        public Criteria andArtifactidIn(List<String> values) {
            addCriterion("artifactid in", values, "artifactid");
            return (Criteria) this;
        }

        public Criteria andArtifactidNotIn(List<String> values) {
            addCriterion("artifactid not in", values, "artifactid");
            return (Criteria) this;
        }

        public Criteria andArtifactidBetween(String value1, String value2) {
            addCriterion("artifactid between", value1, value2, "artifactid");
            return (Criteria) this;
        }

        public Criteria andArtifactidNotBetween(String value1, String value2) {
            addCriterion("artifactid not between", value1, value2, "artifactid");
            return (Criteria) this;
        }

        public Criteria andGroupidIsNull() {
            addCriterion("groupid is null");
            return (Criteria) this;
        }

        public Criteria andGroupidIsNotNull() {
            addCriterion("groupid is not null");
            return (Criteria) this;
        }

        public Criteria andGroupidEqualTo(String value) {
            addCriterion("groupid =", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotEqualTo(String value) {
            addCriterion("groupid <>", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThan(String value) {
            addCriterion("groupid >", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThanOrEqualTo(String value) {
            addCriterion("groupid >=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThan(String value) {
            addCriterion("groupid <", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThanOrEqualTo(String value) {
            addCriterion("groupid <=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLike(String value) {
            addCriterion("groupid like", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotLike(String value) {
            addCriterion("groupid not like", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidIn(List<String> values) {
            addCriterion("groupid in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotIn(List<String> values) {
            addCriterion("groupid not in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidBetween(String value1, String value2) {
            addCriterion("groupid between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotBetween(String value1, String value2) {
            addCriterion("groupid not between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andGitorgIsNull() {
            addCriterion("gitorg is null");
            return (Criteria) this;
        }

        public Criteria andGitorgIsNotNull() {
            addCriterion("gitorg is not null");
            return (Criteria) this;
        }

        public Criteria andGitorgEqualTo(String value) {
            addCriterion("gitorg =", value, "gitorg");
            return (Criteria) this;
        }

        public Criteria andGitorgNotEqualTo(String value) {
            addCriterion("gitorg <>", value, "gitorg");
            return (Criteria) this;
        }

        public Criteria andGitorgGreaterThan(String value) {
            addCriterion("gitorg >", value, "gitorg");
            return (Criteria) this;
        }

        public Criteria andGitorgGreaterThanOrEqualTo(String value) {
            addCriterion("gitorg >=", value, "gitorg");
            return (Criteria) this;
        }

        public Criteria andGitorgLessThan(String value) {
            addCriterion("gitorg <", value, "gitorg");
            return (Criteria) this;
        }

        public Criteria andGitorgLessThanOrEqualTo(String value) {
            addCriterion("gitorg <=", value, "gitorg");
            return (Criteria) this;
        }

        public Criteria andGitorgLike(String value) {
            addCriterion("gitorg like", value, "gitorg");
            return (Criteria) this;
        }

        public Criteria andGitorgNotLike(String value) {
            addCriterion("gitorg not like", value, "gitorg");
            return (Criteria) this;
        }

        public Criteria andGitorgIn(List<String> values) {
            addCriterion("gitorg in", values, "gitorg");
            return (Criteria) this;
        }

        public Criteria andGitorgNotIn(List<String> values) {
            addCriterion("gitorg not in", values, "gitorg");
            return (Criteria) this;
        }

        public Criteria andGitorgBetween(String value1, String value2) {
            addCriterion("gitorg between", value1, value2, "gitorg");
            return (Criteria) this;
        }

        public Criteria andGitorgNotBetween(String value1, String value2) {
            addCriterion("gitorg not between", value1, value2, "gitorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgIsNull() {
            addCriterion("apolloorg is null");
            return (Criteria) this;
        }

        public Criteria andApolloorgIsNotNull() {
            addCriterion("apolloorg is not null");
            return (Criteria) this;
        }

        public Criteria andApolloorgEqualTo(String value) {
            addCriterion("apolloorg =", value, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgNotEqualTo(String value) {
            addCriterion("apolloorg <>", value, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgGreaterThan(String value) {
            addCriterion("apolloorg >", value, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgGreaterThanOrEqualTo(String value) {
            addCriterion("apolloorg >=", value, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgLessThan(String value) {
            addCriterion("apolloorg <", value, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgLessThanOrEqualTo(String value) {
            addCriterion("apolloorg <=", value, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgLike(String value) {
            addCriterion("apolloorg like", value, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgNotLike(String value) {
            addCriterion("apolloorg not like", value, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgIn(List<String> values) {
            addCriterion("apolloorg in", values, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgNotIn(List<String> values) {
            addCriterion("apolloorg not in", values, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgBetween(String value1, String value2) {
            addCriterion("apolloorg between", value1, value2, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andApolloorgNotBetween(String value1, String value2) {
            addCriterion("apolloorg not between", value1, value2, "apolloorg");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterionForJDBCDate("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterionForJDBCDate("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterionForJDBCDate("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterionForJDBCDate("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 18 14:03:56 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbg.generated Tue Jun 18 14:03:56 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}