package com.inclination.scaffold.infrastraction.repository.po;

import java.io.Serializable;

import com.inclination.scaffold.infrastraction.repository.RoleMenuMapper;

public class RoleMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.id
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.roid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private Integer roid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.tmid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private Integer tmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_menu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.id
     *
     * @return the value of role_menu.id
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.id
     *
     * @param id the value for role_menu.id
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.roid
     *
     * @return the value of role_menu.roid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public Integer getRoid() {
        return roid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.roid
     *
     * @param roid the value for role_menu.roid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public void setRoid(Integer roid) {
        this.roid = roid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.tmid
     *
     * @return the value of role_menu.tmid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public Integer getTmid() {
        return tmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.tmid
     *
     * @param tmid the value for role_menu.tmid
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public void setTmid(Integer tmid) {
        this.tmid = tmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roid=").append(roid);
        sb.append(", tmid=").append(tmid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

}