package com.inclination.scaffold.infrastraction.repository.po;

import java.io.Serializable;

public class Tmenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.id
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.mununame
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private String mununame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.content
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmenu.flag
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.id
     *
     * @return the value of tmenu.id
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.id
     *
     * @param id the value for tmenu.id
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.mununame
     *
     * @return the value of tmenu.mununame
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public String getMununame() {
        return mununame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.mununame
     *
     * @param mununame the value for tmenu.mununame
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public void setMununame(String mununame) {
        this.mununame = mununame == null ? null : mununame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.content
     *
     * @return the value of tmenu.content
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.content
     *
     * @param content the value for tmenu.content
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmenu.flag
     *
     * @return the value of tmenu.flag
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmenu.flag
     *
     * @param flag the value for tmenu.flag
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmenu
     *
     * @mbg.generated Sun Jun 02 15:52:19 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mununame=").append(mununame);
        sb.append(", content=").append(content);
        sb.append(", flag=").append(flag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}