package com.inclination.scaffold.infrastraction.repository.po;

import java.io.Serializable;

public class Toolprojecturl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toolprojecturl.id
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toolprojecturl.urlname
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    private String urlname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toolprojecturl.url
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toolprojecturl.name
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toolprojecturl.password
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toolprojecturl.id
     *
     * @return the value of toolprojecturl.id
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toolprojecturl.id
     *
     * @param id the value for toolprojecturl.id
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toolprojecturl.urlname
     *
     * @return the value of toolprojecturl.urlname
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    public String getUrlname() {
        return urlname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toolprojecturl.urlname
     *
     * @param urlname the value for toolprojecturl.urlname
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    public void setUrlname(String urlname) {
        this.urlname = urlname == null ? null : urlname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toolprojecturl.url
     *
     * @return the value of toolprojecturl.url
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toolprojecturl.url
     *
     * @param url the value for toolprojecturl.url
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toolprojecturl.name
     *
     * @return the value of toolprojecturl.name
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toolprojecturl.name
     *
     * @param name the value for toolprojecturl.name
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toolprojecturl.password
     *
     * @return the value of toolprojecturl.password
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toolprojecturl.password
     *
     * @param password the value for toolprojecturl.password
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toolprojecturl
     *
     * @mbg.generated Tue Jun 18 12:44:09 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", urlname=").append(urlname);
        sb.append(", url=").append(url);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}