package com.inclination.scaffold.infrastraction.repository.po;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.loginid
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    private String loginid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userpassword
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    private String userpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.useremil
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    private String useremil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.roid
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    private Integer roid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.loginid
     *
     * @return the value of user.loginid
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public String getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.loginid
     *
     * @param loginid the value for user.loginid
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid == null ? null : loginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userpassword
     *
     * @return the value of user.userpassword
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userpassword
     *
     * @param userpassword the value for user.userpassword
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.useremil
     *
     * @return the value of user.useremil
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public String getUseremil() {
        return useremil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.useremil
     *
     * @param useremil the value for user.useremil
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public void setUseremil(String useremil) {
        this.useremil = useremil == null ? null : useremil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.roid
     *
     * @return the value of user.roid
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public Integer getRoid() {
        return roid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.roid
     *
     * @param roid the value for user.roid
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    public void setRoid(Integer roid) {
        this.roid = roid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jun 02 16:27:40 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginid=").append(loginid);
        sb.append(", username=").append(username);
        sb.append(", userpassword=").append(userpassword);
        sb.append(", useremil=").append(useremil);
        sb.append(", roid=").append(roid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}